name: "ejercicio2"
services:
  filebrowser:
    image: hurlenko/filebrowser
    ports:
      - 8080:8080
    volumes:
      - C:/Users/Guty/Desktop/ejercicio2 docker/DATA_DIR:/data
      - C:/Users/Guty/Desktop/ejercicio2 docker/CONFIG_DIR:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=filebrowser
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
    restart: always
volumes:
  db_data:
  nginx_conf:

